<?php

use yii\db\Migration;

class m160921_214644_elementClasses_relationClasses extends Migration
{
    public function safeUp()
    {
        $contexts = [
            ['Common'],
            ['Construction'],
            ['EngineeringSystem'],
            ['Immovables'],
            ['Interior'],
            ['Material'],
            ['Specialist'],
        ];
        $this->batchInsert('context', ['name'], $contexts);

        $classes = [
            [6, 'material\Material', 'material_Material', ''],
            [6, 'material\Substance', 'material_Substance', ''],

            [2, 'construction\Element', 'construction_Element', ''],
            [2, 'construction\Construction', 'construction_Construction', ''],

            [2, 'construction\BracingElement', 'construction_BracingElement', ''],
            [2, 'construction\Bracing', 'construction_Bracing', ''],
            [2, 'construction\Process', 'construction_Process', ''],
            [2, 'construction\Method', 'construction_Method', ''],
            [2, 'construction\Work', 'construction_Work', ''],
            [2, 'construction\Tool', 'construction_Tool', ''],

            [3, 'engineeringSystem\Element', 'engeneeringSystem_Element', ''],
            [3, 'engineeringSystem\Subsystem', 'engeneeringSystem_Subsystem', ''],
            [3, 'engineeringSystem\Model', 'engeneeringSystem_model', ''],
            [3, 'engineeringSystem\Conductor', 'engeneeringSystem_Conductor', ''],
            [3, 'engineeringSystem\Covering', 'engeneeringSystem_Covering', ''],
            [3, 'engineeringSystem\ControlElement', 'engeneeringSystem_ControlElement', ''],
            [3, 'engineeringSystem\Converter', 'engeneeringSystem_Converter', ''],
            [3, 'engineeringSystem\Sensor', 'engeneeringSystem_Sensor', ''],
            [3, 'engineeringSystem\Accumulator', 'engeneeringSystem_Accumulator', ''],

            [5, 'interior\Element', 'interior_Element', ''],
            [5, 'interior\Assemblage', 'interior_Assemblage', ''],
            [5, 'interior\Solution', 'interior_Solution', ''],
            [5, 'interior\FunctionalZone', 'interior_FunctionalZone', ''],
            [5, 'interior\Subject', 'interior_Subject', ''],
            [5, 'interior\Room', 'interior_Room', ''],
            [5, 'interior\Model', 'interior_Model', ''],
            [1, 'common\Element', 'common_Element', ''],
        ];
        $this->batchInsert('element_class', ['context_id', 'name', 'sysname', 'description'], $classes);

        $relationClass = [
            [1, 'material contains material', 'material1material', ''],
            [2, 'material includes substance', 'material2substance', ''],
            [1, 'substance contains substance', 'substance1substance', ''],
            [2, 'constructionElement includes material', 'constructionElement2material', ''],
            [2, 'bracingElement includes material', 'bracingElement2material', ''],
            [1, 'construction contains constructionElement', 'construction2constructionElement', ''],
            [1, 'construction contains construction', 'construction1construction', ''],
            [2, 'construction includes bracing', 'construction2bracing', ''],
            [2, 'bracingElement includes constructionElement', 'bracing2ConstructionElement', ''],
            [2, 'bracing includes bracingElement', 'bracing2bracingElement', ''],
            [2, 'process goal is constructionElement', 'process2constructionElement', ''],
            [2, 'process goal is bracing', 'process2bracing', ''],
            [2, 'process goal is construction', 'process2construction', ''],
            [2, 'process implementation', 'process2method', ''],
            [2, 'list of works', 'method2work', ''],
            [2, 'work use substance', 'work2substance', ''],
            [2, 'work use material', 'work2material', ''],
            [2, 'work use constructionElement', 'work2constructionElement', ''],
            [2, 'work use tool', 'work2tool', ''],
            [2, 'ESElement inputs', 'ESElementInESElement', ''],
            [2, 'ESElement outputs', 'ESElementOutESElement', ''],
            [2, 'ESElement for substance', 'ESElement2substance', ''],
            [2, 'subsystem for substance', 'subsystem2substance', ''],
            [1, 'subsystem contains ESElement', 'subsystem1ESElement', ''],
            [2, 'process goal is subsystem', 'process2subsystem', ''],
            [2, 'bracing for ESElement', 'bracing2ESElement', ''],
            [2, 'bracing for subsystem', 'bracing2subsystem', ''],
            [1, 'hierarchy of subsystems', 'subsystem1subsystem', ''],
            [2, 'model for subsystem', 'subsystem2ESModel', ''],
            [1, 'assemblage contains interiorElement', 'assemblage1interiorElement', ''],
            [1, 'hierarchy of assemblage', 'interiorElement1interiorElement', ''],
            [2, 'interiorSolution includes assemblage', 'interiorSolution2assemblage', ''],
            [2, 'functionalZone includes assemblage', 'functionalZone2assemblage', ''],
            [2, 'functionalZone has interiorSolution', 'functionalZone2interiorSolutio', ''],
            [2, 'functionalZone for interiorSubject', 'functionalZone2interiorSubject', ''],
            [2, 'interiorRoom has FunctionalZone', 'interiorRoom2FunctionalZone', ''],
            [2, 'interiorRoom has interiorModel', 'interiorRoom2interiorModel', ''],
            [2, 'tool for substance', 'tool2substance', ''],
            [2, 'tool for tool', 'tool2tool', ''],
        ];
        $this->batchInsert('relation_class', ['relation_type_id', 'name', 'sysname', 'description'], $relationClass);

        $elementRelation = [
            ['1', '1', 1],
            ['1', '1', 0],
            ['1', '2', 1],
            ['2', '2', 0],
            ['2', '3', 1],
            ['2', '3', 0],
            ['3', '4', 1],
            ['1', '4', 0],
            ['5', '5', 1],
            ['1', '5', 0],
            ['4', '6', 1],
            ['3', '6', 0],
            ['4', '7', 1],
            ['4', '7', 0],
            ['4', '8', 1],
            ['6', '8', 0],
            ['5', '9', 1],
            ['3', '9', 0],
            ['6', '10', 1],
            ['5', '10', 0],
            ['7', '11', 1],
            ['3', '11', 0],
            ['7', '12', 1],
            ['6', '12', 0],
            ['7', '13', 1],
            ['4', '13', 0],
            ['7', '14', 1],
            ['8', '14', 0],
            ['8', '15', 1],
            ['9', '15', 0],
            ['9', '16', 1],
            ['2', '16', 0],
            ['9', '17', 1],
            ['1', '17', 0],
            ['9', '18', 1],
            ['3', '18', 0],
            ['9', '19', 1],
            ['10', '19', 0],
            ['11', '20', 1],
            ['11', '20', 0],
            ['11', '21', 1],
            ['11', '21', 0],
            ['11', '22', 1],
            ['2', '22', 0],
            ['12', '23', 1],
            ['2', '23', 0],
            ['12', '24', 1],
            ['11', '24', 0],
            ['7', '25', 1],
            ['12', '25', 0],
            ['6', '26', 1],
            ['11', '26', 0],
            ['6', '27', 1],
            ['12', '27', 0],
            ['12', '28', 1],
            ['12', '28', 0],
            ['12', '29', 1],
            ['26', '29', 0],
            ['21', '30', 1],
            ['20', '30', 0],
            ['21', '31', 1],
            ['21', '31', 0],
            ['22', '32', 1],
            ['21', '32', 0],
            ['23', '33', 1],
            ['21', '33', 0],
            ['23', '34', 1],
            ['22', '34', 0],
            ['23', '35', 1],
            ['24', '35', 0],
            ['25', '36', 1],
            ['23', '36', 0],
            ['25', '37', 1],
            ['26', '37', 0],
            ['10', '38', 1],
            ['2', '38', 0],
            ['10', '39', 1],
            ['10', '39', 0],
        ];
        $this->batchInsert('element_class2relation_class', ['element_class_id', 'relation_class_id', 'is_root'], $elementRelation);
    }

    public function safeDown()
    {
    }
}
