<?php
/**
 * Created by daSilva.Rodrigues
 * Date: 05.08.2016
 */

namespace api\modules\engineeringSystem;

/**
 * Class Module
 * @package api\modules\engineeringSystem
 */
class Module extends \yii\base\Module
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}